/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Admin { 'username' : string, 'role' : string }
export interface Member {
  'pin' : string,
  'username' : string,
  'balance' : bigint,
  'name' : string,
  'serialNumber' : bigint,
  'phone' : string,
  'monthlyContribution' : bigint,
}
export interface PaymentRecord {
  'month' : bigint,
  'note' : string,
  'year' : bigint,
  'timestamp' : bigint,
  'amount' : bigint,
}
export interface UpiSettings { 'upiId' : string }
export interface UserProfile {
  'userType' : string,
  'adminInfo' : [] | [Admin],
  'memberInfo' : [] | [Member],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAdmin' : ActorMethod<[Principal, string, string], undefined>,
  'addMember' : ActorMethod<
    [Principal, string, string, string, string, bigint, bigint],
    undefined
  >,
  'addPaymentRecord' : ActorMethod<
    [Principal, bigint, bigint, bigint, string],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteMember' : ActorMethod<[Principal], undefined>,
  'getAdmin' : ActorMethod<[Principal], [] | [Admin]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMember' : ActorMethod<[], [] | [Member]>,
  'getMemberByPrincipal' : ActorMethod<[Principal], [] | [Member]>,
  'getPayments' : ActorMethod<[], Array<PaymentRecord>>,
  'getPaymentsByMember' : ActorMethod<[Principal], Array<PaymentRecord>>,
  'getUpiSettings' : ActorMethod<[], [] | [UpiSettings]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAdmins' : ActorMethod<[], Array<[Principal, Admin]>>,
  'listMembers' : ActorMethod<[], Array<[Principal, Member]>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateMember' : ActorMethod<
    [Principal, string, string, string, bigint, bigint],
    undefined
  >,
  'updatePin' : ActorMethod<[string], undefined>,
  'updateUpiSettings' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];