/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityLog {
  'id' : bigint,
  'action' : string,
  'performed_by' : Principal,
  'timestamp' : bigint,
  'details' : string,
}
export interface DashboardStats {
  'total_collected_this_year' : bigint,
  'total_collected_this_month' : bigint,
  'total_members' : bigint,
  'total_outstanding_balance' : bigint,
}
export interface Member {
  'status' : { 'active' : null } |
    { 'inactive' : null },
  'join_date' : bigint,
  'monthly_amount' : bigint,
  'name' : string,
  'phone' : string,
  'serial_no' : bigint,
}
export interface MonthlyCollection {
  'month' : string,
  'year' : bigint,
  'amount' : bigint,
}
export interface Payment {
  'id' : bigint,
  'date' : bigint,
  'note' : [] | [string],
  'member_phone' : string,
  'upi_txn_id' : [] | [string],
  'amount' : bigint,
}
export interface UPIConfig {
  'description' : string,
  'upi_id' : string,
  'merchant_name' : string,
}
export interface UserProfile { 'name' : string, 'phone' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMember' : ActorMethod<[string, string, bigint, bigint], Member>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteMember' : ActorMethod<[string], undefined>,
  'getActivityLog' : ActorMethod<[], Array<ActivityLog>>,
  'getAllPayments' : ActorMethod<[], Array<Payment>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getMemberByPhone' : ActorMethod<[string], [] | [Member]>,
  'getMonthlyBalance' : ActorMethod<[string, bigint, bigint], bigint>,
  'getMonthlyCollectionData' : ActorMethod<[], Array<MonthlyCollection>>,
  'getPaymentHistory' : ActorMethod<[string], Array<Payment>>,
  'getUPIConfig' : ActorMethod<[], [] | [UPIConfig]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getYearlyBalance' : ActorMethod<[string, bigint], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllMembers' : ActorMethod<[], Array<Member>>,
  'recordPayment' : ActorMethod<
    [string, bigint, bigint, [] | [string], [] | [string]],
    Payment
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setUPIConfig' : ActorMethod<[string, string, string], undefined>,
  'updateMember' : ActorMethod<
    [string, string, bigint, { 'active' : null } | { 'inactive' : null }],
    Member
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];