/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Member = IDL.Record({
  'memberId' : IDL.Nat,
  'name' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'monthlyFee' : IDL.Nat,
});
export const Payment = IDL.Record({
  'status' : IDL.Text,
  'memberId' : IDL.Nat,
  'month' : IDL.Nat,
  'year' : IDL.Nat,
  'amountPaid' : IDL.Nat,
  'paymentId' : IDL.Nat,
  'paymentDate' : IDL.Int,
  'paymentMode' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Stats = IDL.Record({
  'totalCollected' : IDL.Nat,
  'totalMembers' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMember' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'addPayment' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteMember' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deletePayment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
  'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMember' : IDL.Func([IDL.Nat], [IDL.Opt(Member)], ['query']),
  'getPayment' : IDL.Func([IDL.Nat], [IDL.Opt(Payment)], ['query']),
  'getPaymentsByMember' : IDL.Func([IDL.Nat], [IDL.Vec(Payment)], ['query']),
  'getPaymentsByMonthYear' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Payment)],
      ['query'],
    ),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateMember' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Bool],
      [],
    ),
  'updatePayment' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Member = IDL.Record({
    'memberId' : IDL.Nat,
    'name' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'monthlyFee' : IDL.Nat,
  });
  const Payment = IDL.Record({
    'status' : IDL.Text,
    'memberId' : IDL.Nat,
    'month' : IDL.Nat,
    'year' : IDL.Nat,
    'amountPaid' : IDL.Nat,
    'paymentId' : IDL.Nat,
    'paymentDate' : IDL.Int,
    'paymentMode' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Stats = IDL.Record({
    'totalCollected' : IDL.Nat,
    'totalMembers' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMember' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'addPayment' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteMember' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deletePayment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
    'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMember' : IDL.Func([IDL.Nat], [IDL.Opt(Member)], ['query']),
    'getPayment' : IDL.Func([IDL.Nat], [IDL.Opt(Payment)], ['query']),
    'getPaymentsByMember' : IDL.Func([IDL.Nat], [IDL.Vec(Payment)], ['query']),
    'getPaymentsByMonthYear' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Payment)],
        ['query'],
      ),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateMember' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Bool],
        [],
      ),
    'updatePayment' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };