/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Admin = IDL.Record({ 'username' : IDL.Text, 'role' : IDL.Text });
export const Member = IDL.Record({
  'pin' : IDL.Text,
  'username' : IDL.Text,
  'balance' : IDL.Int,
  'name' : IDL.Text,
  'serialNumber' : IDL.Nat,
  'phone' : IDL.Text,
  'monthlyContribution' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'userType' : IDL.Text,
  'adminInfo' : IDL.Opt(Admin),
  'memberInfo' : IDL.Opt(Member),
});
export const PaymentRecord = IDL.Record({
  'month' : IDL.Nat,
  'note' : IDL.Text,
  'year' : IDL.Nat,
  'timestamp' : IDL.Int,
  'amount' : IDL.Nat,
});
export const UpiSettings = IDL.Record({ 'upiId' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAdmin' : IDL.Func([IDL.Principal, IDL.Text, IDL.Text], [], []),
  'addMember' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Int],
      [],
      [],
    ),
  'addPaymentRecord' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteMember' : IDL.Func([IDL.Principal], [], []),
  'getAdmin' : IDL.Func([IDL.Principal], [IDL.Opt(Admin)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMember' : IDL.Func([], [IDL.Opt(Member)], ['query']),
  'getMemberByPrincipal' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(Member)],
      ['query'],
    ),
  'getPayments' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
  'getPaymentsByMember' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PaymentRecord)],
      ['query'],
    ),
  'getUpiSettings' : IDL.Func([], [IDL.Opt(UpiSettings)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAdmins' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, Admin))],
      ['query'],
    ),
  'listMembers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, Member))],
      ['query'],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateMember' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Int],
      [],
      [],
    ),
  'updatePin' : IDL.Func([IDL.Text], [], []),
  'updateUpiSettings' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Admin = IDL.Record({ 'username' : IDL.Text, 'role' : IDL.Text });
  const Member = IDL.Record({
    'pin' : IDL.Text,
    'username' : IDL.Text,
    'balance' : IDL.Int,
    'name' : IDL.Text,
    'serialNumber' : IDL.Nat,
    'phone' : IDL.Text,
    'monthlyContribution' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'userType' : IDL.Text,
    'adminInfo' : IDL.Opt(Admin),
    'memberInfo' : IDL.Opt(Member),
  });
  const PaymentRecord = IDL.Record({
    'month' : IDL.Nat,
    'note' : IDL.Text,
    'year' : IDL.Nat,
    'timestamp' : IDL.Int,
    'amount' : IDL.Nat,
  });
  const UpiSettings = IDL.Record({ 'upiId' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAdmin' : IDL.Func([IDL.Principal, IDL.Text, IDL.Text], [], []),
    'addMember' : IDL.Func(
        [
          IDL.Principal,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Int,
        ],
        [],
        [],
      ),
    'addPaymentRecord' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteMember' : IDL.Func([IDL.Principal], [], []),
    'getAdmin' : IDL.Func([IDL.Principal], [IDL.Opt(Admin)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMember' : IDL.Func([], [IDL.Opt(Member)], ['query']),
    'getMemberByPrincipal' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(Member)],
        ['query'],
      ),
    'getPayments' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
    'getPaymentsByMember' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PaymentRecord)],
        ['query'],
      ),
    'getUpiSettings' : IDL.Func([], [IDL.Opt(UpiSettings)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAdmins' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, Admin))],
        ['query'],
      ),
    'listMembers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, Member))],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateMember' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Int],
        [],
        [],
      ),
    'updatePin' : IDL.Func([IDL.Text], [], []),
    'updateUpiSettings' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };