/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Member = IDL.Record({
  'status' : IDL.Variant({ 'active' : IDL.Null, 'inactive' : IDL.Null }),
  'join_date' : IDL.Int,
  'monthly_amount' : IDL.Nat,
  'name' : IDL.Text,
  'phone' : IDL.Text,
  'serial_no' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ActivityLog = IDL.Record({
  'id' : IDL.Nat,
  'action' : IDL.Text,
  'performed_by' : IDL.Principal,
  'timestamp' : IDL.Int,
  'details' : IDL.Text,
});
export const Payment = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Int,
  'note' : IDL.Opt(IDL.Text),
  'member_phone' : IDL.Text,
  'upi_txn_id' : IDL.Opt(IDL.Text),
  'amount' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'total_collected_this_year' : IDL.Nat,
  'total_collected_this_month' : IDL.Nat,
  'total_members' : IDL.Nat,
  'total_outstanding_balance' : IDL.Nat,
});
export const MonthlyCollection = IDL.Record({
  'month' : IDL.Text,
  'year' : IDL.Nat,
  'amount' : IDL.Nat,
});
export const UPIConfig = IDL.Record({
  'description' : IDL.Text,
  'upi_id' : IDL.Text,
  'merchant_name' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMember' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Int], [Member], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteMember' : IDL.Func([IDL.Text], [], []),
  'getActivityLog' : IDL.Func([], [IDL.Vec(ActivityLog)], ['query']),
  'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getMemberByPhone' : IDL.Func([IDL.Text], [IDL.Opt(Member)], ['query']),
  'getMonthlyBalance' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Int],
      ['query'],
    ),
  'getMonthlyCollectionData' : IDL.Func(
      [],
      [IDL.Vec(MonthlyCollection)],
      ['query'],
    ),
  'getPaymentHistory' : IDL.Func([IDL.Text], [IDL.Vec(Payment)], ['query']),
  'getUPIConfig' : IDL.Func([], [IDL.Opt(UPIConfig)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getYearlyBalance' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Int], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
  'recordPayment' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Int, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [Payment],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setUPIConfig' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateMember' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Variant({ 'active' : IDL.Null, 'inactive' : IDL.Null }),
      ],
      [Member],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Member = IDL.Record({
    'status' : IDL.Variant({ 'active' : IDL.Null, 'inactive' : IDL.Null }),
    'join_date' : IDL.Int,
    'monthly_amount' : IDL.Nat,
    'name' : IDL.Text,
    'phone' : IDL.Text,
    'serial_no' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ActivityLog = IDL.Record({
    'id' : IDL.Nat,
    'action' : IDL.Text,
    'performed_by' : IDL.Principal,
    'timestamp' : IDL.Int,
    'details' : IDL.Text,
  });
  const Payment = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Int,
    'note' : IDL.Opt(IDL.Text),
    'member_phone' : IDL.Text,
    'upi_txn_id' : IDL.Opt(IDL.Text),
    'amount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'phone' : IDL.Text });
  const DashboardStats = IDL.Record({
    'total_collected_this_year' : IDL.Nat,
    'total_collected_this_month' : IDL.Nat,
    'total_members' : IDL.Nat,
    'total_outstanding_balance' : IDL.Nat,
  });
  const MonthlyCollection = IDL.Record({
    'month' : IDL.Text,
    'year' : IDL.Nat,
    'amount' : IDL.Nat,
  });
  const UPIConfig = IDL.Record({
    'description' : IDL.Text,
    'upi_id' : IDL.Text,
    'merchant_name' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMember' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Int],
        [Member],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteMember' : IDL.Func([IDL.Text], [], []),
    'getActivityLog' : IDL.Func([], [IDL.Vec(ActivityLog)], ['query']),
    'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getMemberByPhone' : IDL.Func([IDL.Text], [IDL.Opt(Member)], ['query']),
    'getMonthlyBalance' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Int],
        ['query'],
      ),
    'getMonthlyCollectionData' : IDL.Func(
        [],
        [IDL.Vec(MonthlyCollection)],
        ['query'],
      ),
    'getPaymentHistory' : IDL.Func([IDL.Text], [IDL.Vec(Payment)], ['query']),
    'getUPIConfig' : IDL.Func([], [IDL.Opt(UPIConfig)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getYearlyBalance' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Int], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
    'recordPayment' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Int, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [Payment],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setUPIConfig' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateMember' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Variant({ 'active' : IDL.Null, 'inactive' : IDL.Null }),
        ],
        [Member],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };