/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Member {
  'memberId' : bigint,
  'name' : string,
  'address' : string,
  'phone' : string,
  'monthlyFee' : bigint,
}
export interface Payment {
  'status' : string,
  'memberId' : bigint,
  'month' : bigint,
  'year' : bigint,
  'amountPaid' : bigint,
  'paymentId' : bigint,
  'paymentDate' : bigint,
  'paymentMode' : string,
}
export interface Stats { 'totalCollected' : bigint, 'totalMembers' : bigint }
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMember' : ActorMethod<[string, string, string, bigint], bigint>,
  'addPayment' : ActorMethod<
    [bigint, bigint, bigint, bigint, string, string],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteMember' : ActorMethod<[bigint], boolean>,
  'deletePayment' : ActorMethod<[bigint], boolean>,
  'getAllMembers' : ActorMethod<[], Array<Member>>,
  'getAllPayments' : ActorMethod<[], Array<Payment>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMember' : ActorMethod<[bigint], [] | [Member]>,
  'getPayment' : ActorMethod<[bigint], [] | [Payment]>,
  'getPaymentsByMember' : ActorMethod<[bigint], Array<Payment>>,
  'getPaymentsByMonthYear' : ActorMethod<[bigint, bigint], Array<Payment>>,
  'getStats' : ActorMethod<[], Stats>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateMember' : ActorMethod<
    [bigint, string, string, string, bigint],
    boolean
  >,
  'updatePayment' : ActorMethod<
    [bigint, bigint, bigint, bigint, string, string],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];